---
apiVersion: v1
kind: Service
metadata:
  annotations:
    discovery.3scale.net/discovery-version: v1
    discovery.3scale.net/scheme: http
    discovery.3scale.net/port: "8080"
    fabric8.io/git-commit: 601f89f6a124d84551b26da76145f54e4efae7c1
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    discovery.3scale.net: "true"
    app: demo-rest-gw
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: com.redhat
  name: demo-rest-gw
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-rest-gw
    provider: fabric8
    group: com.redhat
